language: scala
scala:
  - 2.12.6

before_script:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in secrets.zip.enc -out secrets.zip -d
  - git remote add ssh-origin "git@github.com:wellcomecollection/scala-libs.git"

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - project/target
    - storage/target
    - storage_typesafe/target


# Everything below this line is boilerplate that should be reusable,
# unmodified, in any of our Scala library repos.

sudo: false

branches:
  only:
    - master

env:
  global:
    # This forces Python to print everything to stdout/stderr immediately.
    - PYTHONUNBUFFERED=x

services:
  - docker

jobs:
  include:
    - stage: format
    - name: format
      script: ./sbt_release_tooling.py format
    - stage: test
    - name: fixtures
      script: sbt "project fixtures" test
    - name: json
      script: sbt "project json" test
    - name: messaging
      script: sbt "project messaging" dockerComposeUp test dockerComposeStop
    - name: messaging_typesafe
      script: sbt "project messaging_typesafe" test
    - name: monitoring
      script: sbt "project monitoring" test
    - name: monitoring_typesafe
      script: sbt "project monitoring_typesafe" test
    - name: storage
      script: sbt "project storage" dockerComposeUp test dockerComposeStop
    - name: storage_typesafe
    - script: sbt "project storage_typesafe" test
    - stage: release
      script: ./sbt_release_tooling.py release

stages:
  - format
  - test
  - name: release
    if: type = push
