language: scala
scala:
  - 2.12.6

before_script:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in secrets.zip.enc -out secrets.zip -d
  - git remote add ssh-origin "git@github.com:wellcomecollection/scala-libs.git"

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - project/target
    - storage/target
    - storage_typesafe/target


# Everything below this line is boilerplate that should be reusable,
# unmodified, in any of our Scala library repos.

sudo: false

branches:
  only:
    - master

env:
  global:
    # This forces Python to print everything to stdout/stderr immediately.
    - PYTHONUNBUFFERED=x

services:
  - docker

jobs:
  include:
    - stage: format
      env: TASK=format
    - stage: test
      script: sbt dockerComposeUp
    - script: sbt "project fixtures" test
    - script: sbt "project json" test
    - script: sbt "project messaging" test
    - script: sbt "project messaging_typesafe" test
    - script: sbt "project monitoring" test
    - script: sbt "project monitoring_typesafe" test
    - script: sbt "project storage" test
    - script: sbt "project storage_typesafe" test
    - stage: release
      env: TASK=release

script:
  - ./sbt_release_tooling.py "$TASK"

stages:
  - format
  - test
  - name: release
    if: type = push
