steps:
  - command:
      - "./sbt_release_tooling.py format"
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          entrypoint: "/bin/bash"
          network: "host"
          always-pull: true
