steps:
  - label: format
    command: .buildkite/scripts/format.py
    agents:
      queue: "scala"

  - group: "Test"
    steps:
      - label: "test {{ matrix }}"
        command: "./builds/run_sbt_tests.sh {{ matrix }}"
        matrix:
          - "fixtures"
          - "http"
          - "json"
          - "typesafe_app"
          - "monitoring"
          - "monitoring_typesafe"
          - "messaging"
          - "messaging_typesafe"
          - "storage"
          - "storage_typesafe"
          - "elasticsearch"
          - "elasticsearch_typesafe"
          - "sierra"

        agents:
          queue: "scala"

  - wait

  - label: "cut release"
    if: build.branch == "main"
    commands:
      - "python3 .buildkite/scripts/release.py"
    agents:
      queue: nano

  - wait

  - group: "Publish"
    steps:
    - label: "publish {{ matrix }}"
      if: build.branch == "main"
      command: ".buildkite/scripts/publish.py {{ matrix }}"
      matrix:
        - "fixtures"
        - "http"
        - "http_typesafe"
        - "json"
        - "typesafe_app"
        - "monitoring"
        - "monitoring_typesafe"
        - "messaging"
        - "messaging_typesafe"
        - "storage"
        - "storage_typesafe"
        - "elasticsearch"
        - "elasticsearch_typesafe"
        - "sierra"
        - "sierra_typesafe"

      agents:
        queue: "scala"

  - wait

  - label: "open downstream PRs"
    if: build.branch == "main"
    commands:
      - "pip3 install --user boto3 httpx"
      - "python3 .buildkite/scripts/open_downstream_prs.py"
    agents:
      queue: nano
