steps:
  - label: format
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          propagate-environment: true
          entrypoint: "/usr/bin/python3"
    command: "/workdir/.buildkite/scripts/format.py"
  - wait
  - label: test fixtures
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          command: ["project fixtures", "test"]
  - label: test json
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          command: ["project json", "test"]
  - label: test typesafe_app
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          command: ["project typesafe_app", "test"]
  - label: test messaging
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          command: ["project messaging", "dockerComposeUp", "test", "dockerComposeStop"]
  - label: test messaging_typesafe
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          command: ["project messaging_typesafe", "test"]
  - label: test storage
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          command: ["project storage", "dockerComposeUp", "test", "dockerComposeStop"]
  - label: test storage_typesafe
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          command: ["project storage_typesafe", "test"]
  - wait
  - label: cut release
    if: build.branch == "master"
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          propagate-environment: true
          entrypoint: "/usr/bin/python3"
    command: "/workdir/.buildkite/scripts/release.py"
  - wait
  - label: publish fixtures
    if: build.branch == "master"
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          command: ["project fixtures", "publish"]
  - label: publish json
    if: build.branch == "master"
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          command: ["project json", "publish"]
  - label: publish typesafe_app
    if: build.branch == "master"
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          command: ["project typesafe_app", "publish"]
  - label: publish messaging
    if: build.branch == "master"
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          command: ["project messaging", "publish"]
  - label: publish messaging_typesafe
    if: build.branch == "master"
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          command: ["project messaging_typesafe", "publish"]
  - label: publish storage
    if: build.branch == "master"
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          command: ["project storage", "publish"]
  - label: publish storage_typesafe
    if: build.branch == "master"
    plugins:
      - docker#v3.5.0:
          image: "wellcome/sbt_wrapper"
          mount-ssh-agent: true
          volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
          network: "host"
          always-pull: true
          command: ["project storage_typesafe", "publish"]
