version: "2.1"
services:
  dynamodb:
    image: "public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local"
    ports:
      - "45678:8000"
  s3:
    image: "public.ecr.aws/localstack/localstack:4.0.0"
    environment:
      - SERVICES=s3
      - ALLOW_NONSTANDARD_REGIONS=1
    ports:
      - "33333:4566"
