version: "2.1"
services:
  dynamodb:
    image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/peopleperhour/dynamodb"
    ports:
      - "45678:8000"
  s3:
    image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/scality/s3server:mem-latest"
    ports:
      - "33333:8000"

    # We've seen flakiness when this container doesn't start fast enough,
    # and the first few tests to interact with S3 fail.  This uses
    # docker-compose healthchecks to check the container is returning
    # a 401 Unauthorized before continuing.
    # See https://docs.docker.com/compose/compose-file/#/healthcheck
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:33333"]
      interval: 2s
      timeout: 10s
      retries: 5
  azurite:
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports:
      - "10000:10000"
    command: ["azurite", "--blobHost", "0.0.0.0"]