version: "2.1"
services:
  sns:
    image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/wellcome/fake-sns"
    ports:
      - "9292:9292"
  sqs:
    image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/s12v/elasticmq"
    ports:
      - "9324:9324"
      - "4789:9324"