version: "2.1"
services:
  localstack:
    image: "public.ecr.aws/localstack/localstack:2.2.0"
    environment:
      - SERVICES=sns,sqs
      - ALLOW_NONSTANDARD_REGIONS=1
    ports:
      - "4566:4566"
