# .github/workflows/dependency-graph.yml
name: Update Dependency Graph
on:
  push:
    branches:
      - main
  # Lets us resubmit the graph without a commit
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  dependency-graph:
    uses: wellcomecollection/.github/.github/workflows/dependency_graph.yml@main
    secrets: inherit