name: "Report evictions"

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  id-token: write
  issues: write
  pull-requests: write

jobs:
  report-evictions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - fixtures
          - http
          - json
          - typesafe_app
          - monitoring
          - monitoring_typesafe
          - messaging
          - messaging_typesafe
          - storage
          - storage_typesafe
          - elasticsearch
          - elasticsearch_typesafe
          - sierra
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GHA_SCALA_LIBS_ROLE_ARN }}
      - uses: aws-actions/amazon-ecr-login@v2

      - name: Run eviction report for ${{ matrix.service }}
        run: PGP_PASSPHRASE="" ./builds/report_sbt_evictions.sh ${{ matrix.service }}
        continue-on-error: true

      - name: Upload eviction reports
        if: always()  # This ensures it runs even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: evicted_${{ matrix.service }}
          path: .reports/evicted_${{ matrix.service }}

  collate-evictions:
    runs-on: ubuntu-latest
    needs: report-evictions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download eviction reports
        uses: actions/download-artifact@v4
        with:
          path: .reports/

      - name: Collate evictions
        run: |
          mkdir -p .reports
          builds/report_unique_evictions.sh | tee unique_evictions.txt

      - name: Post eviction report comment
        uses: actions/github-script@v6
        with:
          script: |
            const postComment = require('./.github/scripts/post-eviction-report-comment.js');
            await postComment(github, context);
